In [82]:
import numpy as np

In [83]:
a = np.array([1,5,6,8])
b=[1,5,6,8]
c = np.array([1,2,3,4])
a*5

array([ 5, 25, 30, 40])

In [84]:
b*5

[1, 5, 6, 8, 1, 5, 6, 8, 1, 5, 6, 8, 1, 5, 6, 8, 1, 5, 6, 8]

In [85]:
a*c

array([ 1, 10, 18, 32])

In [86]:
d = np.arange(10)
d[2:8:3]

array([2, 5])

In [87]:
d[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [88]:
d[3:5] = 0
d

array([0, 1, 2, 0, 0, 5, 6, 7, 8, 9])

In [89]:
I = np.array([[1,2,3],[0,0,0],[3,2,1]])
print(len(I.shape),I.shape)

2 (3, 3)


In [90]:
I[0:2,0:2]

array([[1, 2],
       [0, 0]])

In [91]:
I[0:2,0:2] +=5
I

array([[6, 7, 3],
       [5, 5, 0],
       [3, 2, 1]])

In [92]:
for row in I:
  for column in row:
    print(column)

6
7
3
5
5
0
3
2
1


In [93]:
for x in np.nditer(I):
  print(x)

6
7
3
5
5
0
3
2
1


In [94]:
I.flatten()

array([6, 7, 3, 5, 5, 0, 3, 2, 1])

In [95]:
for i,x in np.ndenumerate(I):
  print(i,x)

(0, 0) 6
(0, 1) 7
(0, 2) 3
(1, 0) 5
(1, 1) 5
(1, 2) 0
(2, 0) 3
(2, 1) 2
(2, 2) 1


In [96]:
for posizione,x in np.ndenumerate(I):
  print(posizione,x)
  i,j = posizione
  # I[i,j] = 0 # resetta la matrice
I.T
  

(0, 0) 6
(0, 1) 7
(0, 2) 3
(1, 0) 5
(1, 1) 5
(1, 2) 0
(2, 0) 3
(2, 1) 2
(2, 2) 1


array([[6, 5, 3],
       [7, 5, 2],
       [3, 0, 1]])

In [97]:
F=I.copy() #creo una copia della matrice (un'immagine)
for posizione,x in np.ndenumerate(I):
  i,j = posizione
  F[i,j] = I[j,i]
F

array([[6, 5, 3],
       [7, 5, 2],
       [3, 0, 1]])

In [98]:
I = np.arange(40000)
I = I.reshape((200,200))

I = np.zeros_like(I).astype(np.uint16)
I[50:100, 50:100] = 100
I[:,70:80] +=100
I[:100:5] +=100

import cv2
cv2.imshow("I",I) #.astype(np.float32)
cv2.waitKey(0)

-1

In [99]:
I = cv2.imread("download.jpeg")
I.shape

(183, 276, 3)

In [115]:
#I[:,:,0] = 0 # tolgo il blu
#I[:,:,[0,1] = 0 # tolgo il verde
#I[:,:,[0,2]] = 0 # tolgo il rosso

I[:60,:,[0,2]] = 0
I[120:,:,[0,1]] = 0

I[100:,180:]=[50,0,150]

I[:,:,2]+=40 #vado a saturare il rosso

I//=2
I+=128

I[I>255]=255
#cv2.imshow("I",I.astype(np.uint8))
#cv2.imshow("I",(I.mean(2).T).astype(np.uint8))
cv2.imshow("I",(I.reshape(366,-1,3)).astype(np.uint8))
cv2.waitKey(0)

-1